[project]
name = "ocr-guia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=12.2.0",
    "pyinstaller>=6.20.0",
    "pymupdf>=1.27.2.3",
    "pystray>=0.19.5",
    "rapidocr-onnxruntime>=1.4.4",
    "requests>=2.34.2",
    "watchdog>=6.0.0",
]
